<?php

/**
 * Example function.
 */

function _drush_execute_command($command = NULL, $bundle = NULL, $additional_option_array = array()) {
    //$limit as zero means all
    require_once 'src/ael_backlog_object.php';
    $label = new ael_backlog_object($command, $bundle, $additional_option_array);
    // $label = new ael_backlog_object($bundle, $command, $additional_option_array);
    $label->unpack();
    // switch instead of if-else to make more extensible
    switch ($label->output_message_type) {
        case 'success':
            $limit = $limit == 'EEMPTY' ? 0:$limit;
            $limit = $limit == 'all' ? 0:$limit;
            $type = 'success';
            $type_debug_string = $label->output_message_type;
            // $message = 'Okay, I\'ll Compose the SQL';
            $message = $label->output_message;
            break;

        default:
            $type = 'error';
            $type_debug_string = $label->output_message_type;
            $command = $command == NULL?'NNULL':$command;
            // $message = 'The "' . $command . '" command is not supported, something went very wrong. Please asks for assistance.';
            $message = $label->output_message;
            break;
    }
    $message .= " [$limit]";
  drupal_set_message(t($message), $type);
  drupal_set_message(t("[message set {$type_debug_string}]"), $type);
  $test_output_array = array(
    'Feather'=>'Named for his Tail',
    'Marcy'=>'Named for Mt. Marcy in the Adirondacks',
    'Chester'=>'Named for Chester Creek',
    'Marais'=>'Named for Grand Marais on the North Shore of Lake Superior',
    );
  // $label->output_string =  '<pre>' . print_r($test_output_array, TRUE) . '</pre>';
  drush_print($label->output_string);
}